### ISSUE TITLE
Brillant code. I am trying improving add BR and other locations.

### ISSUE THREAD

**Issue by marciomvm** [sneakykiwi/League-of-Legends-AccountCreator#2]
I did some changes for working for BR accounts but I am struggling to figure out the end post to singup-api.

Do you have an idea what I am missing?
![image](https://user-images.githubusercontent.com/34646575/73596283-b8316d00-4518-11ea-8f3c-9dfbaf0e0c30.png)

I changed the locale to PT, pt_BR, etc... and I just got Responde[409],
This signup-API support other locations? I tried to find some doc about signup API without any success.

If I find the solution I will make a Pull request if want to put this region too.

Many Thanks.

**Comment by sneakykiwi** [comment]
Hello, I have added BR and I will update it soon
